spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /console

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        foramt_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  #  cloud:
  #    kubernetes:
  #      discovery:
  #        all-namespaces: true
  application:
    name: product-service

server:
  port: 8080